import { Inter, Montserrat } from "next/font/google";
import styles from "./global.css";
import Header from "@/src/components/Header/Header";
import Footer from "@/src/components/Footer/Footer";

const inter = Inter({
    subsets: ["latin"],
    variable: '--font-inter',
});

 const montserrat = Montserrat({
    subsets: ['latin'],
    variable: '--font-montserrat',
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="ru">
            <body className={`${inter.variable} ${montserrat.variable}`}>
                <Header/>
                {children}
                <Footer/>
             </body>
        </html>
    );
}
